name: built_value_generator
version: 5.4.3
description: >
  Value types with builders, Dart classes as enums, and serialization.
  This library is the dev dependency.
authors:
- David Morgan <davidmorgan@google.com>
homepage: https://github.com/google/built_value.dart

environment:
  sdk: '>=2-0-0-dev <2.0.0'

dependencies:
  analyzer: '>=0.29.0 <0.32.0'
  analyzer_plugin: '0.0.1-alpha.0'
  build: ^0.12.0
  built_collection: '>=2.0.0 <4.0.0'
  built_value: ^5.4.3
  source_gen: '>=0.7.4 <0.9.0'
  quiver: '>=0.21.0 <0.30.0'

dev_dependencies:
  build_test: ^0.10.0
  build_runner: ^0.7.9
  test: any
